### PR TITLE
 docs(readme): add title widget 

### PR DESCRIPTION
**Pull request by byklyci**

### CODE REVIEW

**Comment by okyksl** [comment]
@nazmicancalik @byklyci shouldn't we change the commit title to something like:

> docs(readme): add title widget

**Comment by byklyci** [comment]
I cahnged the title @okyksl @nazmicancalik

**Comment by okyksl** [comment]
Could you also delete reference to `issue #24`? Sorry for the chore work.

**Comment by byklyci** [comment]
I changed also commit title. Please review it.

**Pull request merged**
