### PR TITLE
Feature/frontend/style

### PR DESCRIPTION
**Pull request by kemaltulum**
I removed www folder

### CODE REVIEW

**Comment by serkan-ozel-2015400123** [comment]
Good work let me check this branch

**Comment by serkan-ozel-2015400123** [comment]
@kemaltulum  Nice work but I have a question on event create page there is an error when I press share button (event create post triggered) server returns 503 unavailable

**Comment by serkan-ozel-2015400123** [comment]
Also, what about user profile shouldn't we add it?  According to  #158 we should. And what about # 159 ? I think we should try to do it later on. @bounswe/bounswe2018group9

**Comment by serkan-ozel-2015400123** [comment]
Another comment: 
The image of an event in feed is different from when you click it in detail page. Is it a problem for demo?

**Comment by okyksl** [comment]
Let's try to merge **event creation** only for now.

**Comment by serkan-ozel-2015400123** [comment]
@okyksl  Other than event-create 503, everything is fine with this pr

**Comment by serkan-ozel-2015400123** [comment]
I think that is related to backend, so go ahead and merge this for now ?

**Comment by serkan-ozel-2015400123** [comment]
**Can 503 error occur due to the fact that we don't send exactly these properties in eventAdd() function in Event controller?**
```
var event = new Event({
    name: req.body.name,
    price: req.body.price,
    owner: req.body.owner,
    description: req.body.description,
    date: req.body.date
  })
```

**Comment by serkan-ozel-2015400123** [comment]
Let me try changing data we are posting before merging this.

**Comment by serkan-ozel-2015400123** [comment]
Yes it's due to that I am pushing the changes @kemaltulum  @okyksl  don't merge yet

**Comment by kemaltulum** [comment]
> Another comment:
> The image of an event in feed is different from when you click it in detail page. Is it a problem for demo?

for now it is acceptable I think

**Pull request merged**
