### PR TITLE
Profile page is implemented and ready to fly 🚀 after your review

### PR DESCRIPTION
**Pull request by serkan-ozel-2015400123**
We are integrating profile page int our app, head changes in this pr,

- Profile page is created 
- Added loading module to profile page while loading user information
- Menu buttons are put in a list and profile button is added
- Profile page has back button to feed
- In profile page, image, name and e mail shown 
- Get user data in auth service to show

Feel free to comment

### CODE REVIEW

**Comment by serkan-ozel-2015400123** [comment]
You are right, modularization would be more clear. On it. I will also solve conflict by rebasing again

**Comment by okyksl** [comment]
One more thing: should we merge **profile module** with **event module**? **Event module** is a misnomer and also, **feed**, **profile** and **event** pages will always be loaded and needed together.

**Comment by okyksl** [comment]
I mean move all **event module** inside your **profile module** maybe?

**Comment by serkan-ozel-2015400123** [comment]
You are right and it sound good. I am changing the structure and adjusting the routes a bit then. I will commit soon :)

**Comment by serkan-ozel-2015400123** [comment]
A question:

When I am in feed, I am in events module so, I press profile button which has href = /profile
at this moment because I am in events module it thinks that I am trying to access an event whose id is profile 

How can I solve this ? 

I need some time if I need to solve this alone :)

**Comment by serkan-ozel-2015400123** [comment]
After resolving this open I will open pr again

**Comment by serkan-ozel-2015400123** [comment]
Please from now on use routerLink instead of href because it causes not to reload whole page. Instead it smoothly changes the content of the already loaded page. Angular is a single page application and does not need reloads.

I have changed the structure and opening the pr again. Hope this is good for you now @okyksl

**Comment by serkan-ozel-2015400123** [comment]
closing, interests will be added

**Pull request closed without merging**
